### ISSUE TITLE
Set up live reload with Webpack

### ISSUE THREAD

**Issue by jbkuczma** [jbkuczma/NBAreact#30]
Want to set up live reload and hot reloading for webpack with React

**Comment by jbkuczma** [comment]
Might have to scrape current webpack setup and start from scratch since nothing seems to work right now.

**Comment by kurtfurbush** [comment]
I forked this code and got the webpack hot reloading setup

**Comment by jbkuczma** [comment]
Closing due to removal of Web App. Decided this repo should consist only of the React Native version of the app.
