### ISSUE TITLE
ios error

### ISSUE THREAD

**Issue by sitexa** [jbkuczma/NBAreact#35]
Bundling `index.ios.js`
  Transforming modules  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░  99.0% (391/393)...(node:11817) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 668): UnableToResolveError: Unable to resolve module `./App/Assets/Images/back_button_white.png` from `/Users/open/NodeProjects/react-projects/NBAreact/App/NBAreact.js`: Directory /Users/open/NodeProjects/react-projects/NBAreact/App/App/Assets/Images/back_button_white.png doesn't exist

**Comment by YogaXiong1** [comment]
del './App '  in NBAreact.js.
'./App/Assets/Images/back_button_white.png'  => '/Assets/Images/back_button_white.png'

**Comment by YogaXiong1** [comment]
del `./App/` in NBAreact.js.
```./App/Assets/Images/back_button_white.png``` => ```./Assets/Images/back_button_white.png```

**Comment by jbkuczma** [comment]
thanks for finding this @sitexa and thanks for the quick suggestion @YogaXiong1. 5b584cc fixes this.
