### ISSUE TITLE
The detail view of players and their stats should have a fixed column at the left that always shows that row's player. 

### ISSUE THREAD

**Issue by fiveNinePlusR** [jbkuczma/NBAreact#72]
when scrolling to the right you lose context of which player the stats are representing. might be nice to prevent diagonal scrolling as well as it makes it feel unpolished.

**Comment by jbkuczma** [comment]
Great idea. I have the same thoughts about losing context of the players so that is a feature I would like to implement in the next release.

Regarding the diagonal scrolling, that should be fixed with the release of v2.3.
